### ISSUE TITLE
Cannot find module '/D:/workspace/nuxt3-aos/node_modules/jiti/lib/index.js' 

### ISSUE THREAD

**Issue by disonwei** [17630966776/nuxt3-aos#1]
It happened wrong!

 ERROR  Cannot find module '/D:/workspace/nuxt3-aos/node_modules/jiti/lib/index.js'                                                                                                                                      2:39:10 PM
Require stack:
- /Users/dison/dison/project/TimeDiary/TimeDiary_Nuxt/node_modules/nuxt3-aos/dist/module.mjs

**Comment by 17630966776** [comment]
I have fixed it in the latest version, please install the latest version to use
